config/routes.rb
ZhmurkoTest::Application.routes.draw do

  resources :settings

  root :to => "settings#index"

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  validates :caption, :presence => true, :uniqueness => true
#  before_save :adjust_value_type

  def converted_value
    if value.to_i.to_s == value
      return value.to_i
    end
    if value =~ %r{(\d{1,2})[/\-](\d{1,2})[/\-](\d{1,4}) (\d{1,2}):(\d{2})}
      return DateTime.new($3.to_i, $2.to_i, $1.to_i, $4.to_i, $5.to_i)
    end
    if value =~ %r{(\d{1,2})[/\-](\d{1,2})[/\-](\d{1,4})}
      return Date.new($3.to_i, $2.to_i, $1.to_i)
    end
    value # just a String
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/configuration_controller.rb
class ConfigurationController < ApplicationController
  def index
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  # GET /settings
  # GET /settings.xml
  def index
    @settings = Setting.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @settings }
    end
  end

  # GET /settings/1
  # GET /settings/1.xml
  def show
    @setting = Setting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @setting }
    end
  end

  # GET /settings/new
  # GET /settings/new.xml
  def new
    @setting = Setting.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @setting }
    end
  end

  # GET /settings/1/edit
  def edit
    @setting = Setting.find(params[:id])
  end

  # POST /settings
  # POST /settings.xml
  def create
    @setting = Setting.new(params[:setting])

    respond_to do |format|
      if @setting.save
        format.html { redirect_to(@setting, :notice => 'Setting was successfully created.') }
        format.xml  { render :xml => @setting, :status => :created, :location => @setting }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @setting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /settings/1
  # PUT /settings/1.xml
  def update
    @setting = Setting.find(params[:id])

    respond_to do |format|
      if @setting.update_attributes(params[:setting])
        format.html { redirect_to(@setting, :notice => 'Setting was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @setting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.xml
  def destroy
    @setting = Setting.find(params[:id])
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to(settings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/configuration_helper.rb
module ConfigurationHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/configuration/index.html.haml
%h1 Configuration
-for setting in @settings do
  %label 
    =setting.caption

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
 %head
  %title ZhmurkoTest
  = stylesheet_link_tag :all
  = javascript_include_tag :defaults
  = csrf_meta_tag
 %body
  = yield

app/views/settings/_form.html.haml
= form_for @setting do |f|
  -if @setting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@setting.errors.count, "error")} prohibited this setting from being saved:"
      %ul
        - @setting.errors.full_messages.each do |msg|
          %li= msg

  .actions
  %table
    %tr
      %td
        %label{:for => "caption"} Caption
      %td
        = f.text_field :caption
    %tr
      %td
        %label{:for => "value"} Value
      %td
        = f.text_area :value, :rows => 4, :cols => 20
      %td.hint 
        Supported formats are String, Integer, Date and DateTime: 
        "sample", 
        42, 
        14-04-1982, 
        01/01/2011 19:30
  = f.submit 'Save'

app/views/settings/edit.html.haml
%h1 Editing setting

= render 'form'

= link_to 'Show', @setting
\|
= link_to 'Back', settings_path

app/views/settings/index.html.haml
%h1 Listing settings

%table
  %tr
    %th Parameter 
    %th Type
    %th Value

  - @settings.each do |setting|
    %tr
      %td= link_to(setting.caption, setting)+":"
      %td= setting.converted_value.class
      %td= setting.value

%br

= link_to 'New Setting', new_setting_path

app/views/settings/new.html.haml
%h1 New setting

= render 'form'

= link_to 'Back', settings_path

app/views/settings/show.html.haml
%p#notice= notice

%h1= @setting.caption
%p== Value: #{@setting.value}

= link_to 'Edit', edit_setting_path(@setting)
\|
= link_to 'Destroy', @setting, :confirm => 'Are you sure?', :method => :delete
\|
= link_to 'Back', settings_path